services:
  site:
    build:
      context: .
      target: runtime
    ports:
      - '8011:8011'
    volumes:
      - ./_src:/app
      - /app/node_modules
  test:
    build:
      context: .
      target: test
    profiles:
      - test
  test-parallel:
    build:
      context: .
      target: verify-parallel
    profiles:
      - test
